name: extra_mile
description: "COMP4206 Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_database: ^10.4.6
  firebase_auth: ^4.19.2
  gap: ^3.0.1
  fluentui_icons: ^1.0.0
  flutter_local_notifications: ^17.0.1
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.12
  android_intent: ^2.0.2
  flutter_rating_bar: ^4.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.17.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: "launcher_icon"
  iso: true
  image_path: "assets/images/extra-mile-logo.png"
  min_sdk_androide: